#홈페이지에서 API서비스 신청시 받은 Appkey, Appsecret 값 설정
APP_KEY: "PS6bXcHDWezqJD2o0iUFkAMJHB8Sj93n7rMt"
APP_SECRET: "QelQZ5O6gykfudIbXA72AWxNYLi5Uv5WBs2ZmUgnjuX+fhU3sfmB/wMWq1Si+WsVHiAeqCS4On2XSkU0rp7Su5oEd2fsIs5ZxeNvlMXt2hp6Kgcei12PGiwBO0Q3QpDTWLn55l9WGSlLVLoJMNmKUmtlN+haa3zNZOaVChHxPsp7bD4gzKM="

#계좌번호 앞 8자리
CANO: "73445792"
#계좌번호 뒤 2자리
ACNT_PRDT_CD: "01"

#실전투자
URL_BASE: "https://openapi.koreainvestment.com:9443"
#모의투자
# URL_BASE: "https://openapivts.koreainvestment.com:29443"

#디스코드 웹훅 URL
DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1061659166298611773/CoFjAo62tuDAWKT1wozvbgqrr8bT7eQ_WIuld0zfmQ7w-PYVZxOrq9YBKPt3YvfK7rXn"
